// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyATu8DUaAKXHMYRLmw5-UNZGVwsrhsF2tg",
    authDomain: "chat-app-3203d.firebaseapp.com",
    projectId: "chat-app-3203d",
    storageBucket: "chat-app-3203d.appspot.com",
    messagingSenderId: "671977107611",
    appId: "1:671977107611:web:8c00af6124439ea0a1d63e",
    measurementId: "G-NNFTWYRKGP",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHgJ-nKNMl7iKcIlA4dAp_V3fzJ5fgnqM',
    appId: '1:671977107611:android:bbe3cbf558dd845fa1d63e',
    messagingSenderId: '671977107611',
    projectId: 'chat-app-3203d',
    storageBucket: 'chat-app-3203d.appspot.com',
  );
}
